CREATE TABLE `appointment` (
  `ref` int(4) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `date` datetime NOT NULL,
  `client_id` int NOT NULL,
  `service_id` int NOT NULL,
  `staff_id` int NOT NULL,
  `start_time` time NOT NULL,
  `end_time_expected` time NOT NULL,
  `end_time` time DEFAULT NULL,
  `price_quoted` decimal(10,0) NOT NULL,
  `price_full` decimal(10,0) DEFAULT NULL,
  `discounted` decimal(10,0) DEFAULT NULL,
  `price_final` decimal(10,0) DEFAULT NULL,
  `date_booked` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `booked_by` varchar(45) NOT NULL,
  `cancelled` tinyint NOT NULL DEFAULT '0',
  `cancelled_reason` varchar(144) DEFAULT NULL,
  PRIMARY KEY (`ref`),
  KEY `fk_appointment_client_client_id_idx` (`client_id`),
  KEY `fk_appointment_staff_staff_id_idx` (`staff_id`),
  KEY `fk_appointment_service_service_id_idx` (`service_id`),
  KEY `fk_appointment_service_price_quoted_idx` (`price_quoted`),
  CONSTRAINT `fk_appointment_client_client_id` FOREIGN KEY (`client_id`) REFERENCES `client` (`id`),
  CONSTRAINT `fk_appointment_service_service_id` FOREIGN KEY (`service_id`) REFERENCES `service` (`id`),
  CONSTRAINT `fk_appointment_staff_staff_id` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`id`)
)